### ISSUE TITLE
Warning! when I try to enable plugin

### ISSUE THREAD

**Issue by josiahdowdy** [jhlothamer/godot_helper_pack#3]
Hi, I get the following error when I try to load your plugin in Godot:

"Unable to load addon script from path: 'res://addons/godot_helper_pack-master/helper_pack_project/addons/godot_helper_pack/godot_helper_pack_plugin.gd'. This might be due to a code error in that script.
Disabling the addon at 'res://addons/godot_helper_pack-master/helper_pack_project/addons/godot_helper_pack/plugin.cfg' to prevent further errors."

When I check the code in the 'godot_helper_pack_plugin.gd' file, my error showing in VSCode is in line 5:

const DISTRIBUTION_EDITOR_PLUGIN_SCENE = preload("res://addons/godot_helper_pack/core/2d/util/distribution/distribution_editor_plugin.tscn")

"can't preload source at path"

Maybe I'm missing something obvious here but do you have any thoughts? Thanks...

**Comment by jhlothamer** [comment]
It seems to indicate that the plugin scene file being preloaded isn't there.  But if you've obtained the latest from the repo that shouldn't be an issue.  Can you attach a zip file of your project or make a github repo available to me to see the issue in action?  If the project is too big or not something you want to be public, then can you recreate the issue in a new project and make that available?  It's the best way for me to see what you are seeing.

Thanks!

**Comment by josiahdowdy** [comment]
Hey sorry it was my mistake. I didn't follow your step 2 direction and had copied in the root folder instead of just the 'godot_helper_pack' folder. Thanks for your great addon!
